update: add wait time to complete the action for automation workflow

diff --git a/.github/workflows/develop.yml b/.github/workflows/develop.yml
--- a/.github/workflows/develop.yml
+++ b/.github/workflows/develop.yml
@@ -155,6 +155,22 @@ jobs:
             -H "Accept: application/vnd.github.v3+json" \
             https://api.github.com/repos/InsiteSoftware/mobile-automation/dispatches \
             -d "$PAYLOAD"
+      - name: Wait for iOS Automation Workflow to Complete
+        run: |
+          STATUS="queued"
+          while [[ -z "$STATUS" || "$STATUS" == "null" || "$STATUS" == "queued" || "$STATUS" == "in_progress" ]]; do
+            sleep 5
+            STATUS=$(curl -s -H "Authorization: Bearer ${{ secrets.my_pat }}" \
+                          -H "Accept: application/vnd.github+json" \
+                          https://api.github.com/repos/InsiteSoftware/mobile-automation/actions/runs \
+                          | jq -r '.workflow_runs[] | select(.name == "iOS Automation Testing") | .conclusion' | head -n 1)
+            sleep 25
+          done
+          if [[ "$STATUS" != "success" ]]; then
+            echo "iOS Automation Workflow failed."
+            exit 1
+          fi
+          echo "iOS Automation Workflow completed successfully."
   android:
     runs-on: macos-latest
     outputs:
@@ -277,3 +293,19 @@ jobs:
             -H "Accept: application/vnd.github.v3+json" \
             https://api.github.com/repos/InsiteSoftware/mobile-automation/dispatches \
             -d "$PAYLOAD"
+      - name: Wait for Android Automation Workflow to Complete
+        run: |
+          STATUS="queued"
+          while [[ -z "$STATUS" || "$STATUS" == "null" || "$STATUS" == "queued" || "$STATUS" == "in_progress" ]]; do
+            sleep 5
+            STATUS=$(curl -s -H "Authorization: Bearer ${{ secrets.my_pat }}" \
+                          -H "Accept: application/vnd.github+json" \
+                          https://api.github.com/repos/InsiteSoftware/mobile-automation/actions/runs \
+                          | jq -r '.workflow_runs[] | select(.name == "Android Automation Testing") | .conclusion' | head -n 1)
+            sleep 25
+          done
+          if [[ "$STATUS" != "success" ]]; then
+            echo "Android Automation Workflow failed."
+            exit 1
+          fi
+          echo "Android Automation Workflow completed successfully."
